-- ============================================================
-- EV Fleet Charging & Battery Health - Snowflake Warehouse Setup
-- ============================================================

CREATE WAREHOUSE IF NOT EXISTS EV_FLEET_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS EV_FLEET_DB;
CREATE SCHEMA IF NOT EXISTS EV_FLEET_DB.ANALYTICS;

USE WAREHOUSE EV_FLEET_WH;
USE DATABASE EV_FLEET_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_VEHICLE (
    VEHICLE_ID          VARCHAR(10) PRIMARY KEY,
    VEHICLE_MODEL        VARCHAR(50),
    FLEET_NAME           VARCHAR(50),
    BATTERY_CAPACITY_KWH  NUMBER(5,1)
);

CREATE OR REPLACE TABLE DIM_DRIVER (
    DRIVER_ID   VARCHAR(10) PRIMARY KEY,
    VEHICLE_ID  VARCHAR(10) REFERENCES DIM_VEHICLE(VEHICLE_ID)
);

CREATE OR REPLACE TABLE DIM_STATION (
    STATION_ID        VARCHAR(10) PRIMARY KEY,
    CHARGING_STATION  VARCHAR(50),
    CITY              VARCHAR(30)
);

CREATE OR REPLACE TABLE DIM_DATE (
    CHARGING_DATE  DATE PRIMARY KEY,
    DAY_OF_WEEK    VARCHAR(15),
    MONTH          VARCHAR(15),
    IS_WEEKEND     BOOLEAN
);

CREATE OR REPLACE TABLE FACT_CHARGING_SESSIONS (
    SESSION_ID              VARCHAR(10) PRIMARY KEY,
    VEHICLE_ID              VARCHAR(10) REFERENCES DIM_VEHICLE(VEHICLE_ID),
    DRIVER_ID               VARCHAR(10) REFERENCES DIM_DRIVER(DRIVER_ID),
    STATION_ID              VARCHAR(10) REFERENCES DIM_STATION(STATION_ID),
    CHARGING_DATE           DATE REFERENCES DIM_DATE(CHARGING_DATE),
    CHARGING_HOUR           NUMBER(2,0),
    CHARGING_TYPE           VARCHAR(10),
    WEATHER                 VARCHAR(15),
    BATTERY_LEVEL_BEFORE    NUMBER(3,0),
    BATTERY_LEVEL_AFTER     NUMBER(3,0),
    BATTERY_DELTA_PCT       NUMBER(3,0),
    CHARGING_DURATION_MIN   NUMBER(5,0),
    ENERGY_CONSUMED_KWH     NUMBER(6,2),
    CHARGING_COST           NUMBER(8,2),
    COST_PER_KWH            NUMBER(6,2),
    CHARGING_SPEED_KW       NUMBER(6,2),
    BATTERY_TEMPERATURE     NUMBER(4,1),
    SOH                     NUMBER(5,2),
    SOH_CATEGORY            VARCHAR(20),
    ODOMETER_KM             NUMBER(8,0),
    DISTANCE_TRAVELLED_KM   NUMBER(6,0),
    IS_PEAK_HOUR            BOOLEAN,
    IS_WEEKEND              BOOLEAN,
    INSIGHT_FLAG            VARCHAR(100)
);

CREATE OR REPLACE FILE FORMAT CSV_STANDARD
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE;
   
    SELECT COUNT(*) FROM EV_FLEET_DB.ANALYTICS.FACT_CHARGING_SESSIONS;